- source/includes/users/_list.md.erb
I updated API documentation after close this issue https://github.com/Teamtailor/teamtailor/pull/2301
> Add department filter to Users/List_users section

- source/includes/_pagination.md.erb
> Specify how the pagination params work

- source/includes/_examples.md.erb
> Example of pagination

- source/includes/_changelog.md.erb
- source/includes/users/_index.md.erb
For this PR https://github.com/Teamtailor/teamtailor/pull/3967/
> Add user jobs relationship

- source/includes/candidates/_index.md.erb
Connected with https://github.com/Teamtailor/teamtailor/pull/4075
> Add send_welcome_message attribute for create-only candidate

- source/includes/jobs/_index.md.erb
Connected to https://github.com/Teamtailor/teamtailor/pull/4095
> End-date doesn't require admin permission again

- source/includes/_auth.md.erb
Missing 'read' word in sentence in Authentication chapter
> Missing 'read' word in sentence

- source/includes/users/_index.md.erb
Connected to https://github.com/Teamtailor/teamtailor/issues/4521
> Let update user by passing picture url

- source/includes/_changelog.md.erb
- source/includes/_examples.md.erb
- source/includes/jobs/_create.md.erb
- source/includes/jobs/_index.md.erb
- source/includes/jobs/_list.md.erb
- source/includes/jobs/_read.md.erb
- source/includes/jobs/_update.md.erb
Support multiple locations for job. Connected with https://github.com/Teamtailor/teamtailor/pull/4106
> Job has multiple locations, single location is deprecated

- source/includes/_changelog.md.erb
- source/includes/jobs/_index.md.erb
More details and related code changes:
https://github.com/Teamtailor/teamtailor/commit/65b8bd03c33b7bf385a4986fce41b3ce48bfb7a1
> Add mailbox attribute to JobResurce

- source/includes/_changelog.md.erb
- source/includes/todos/_create.md.erb
- source/includes/todos/_delete.md.erb
- source/includes/todos/_index.md.erb
- source/includes/todos/_list.md.erb
- source/includes/todos/_read.md.erb
- source/includes/todos/_update.md.erb
- source/index.html.md.erb
Adding a new todo resource.
Connected with https://github.com/Teamtailor/teamtailor/pull/5201
> Add todos resource

- source/includes/_changelog.md.erb
- source/includes/activities/_index.md.erb
- source/includes/activities/_list.md.erb
- source/includes/activities/_read.md.erb
- source/index.html.md.erb
Adding a new activity resource.
Connected with https://github.com/Teamtailor/teamtailor/pull/5212
> Add activities resource

- source/includes/_changelog.md.erb
- source/includes/partner_results/_index.md.erb
- source/includes/partner_results/_list.md.erb
- source/includes/partner_results/_read.md.erb
- source/index.html.md.erb
Adding a new partner-results resource.
Connected with https://github.com/Teamtailor/teamtailor/pull/5243
> Add partner-results resource

- source/includes/_changelog.md.erb
- source/includes/referrals/_index.md.erb
- source/includes/referrals/_list.md.erb
- source/includes/referrals/_read.md.erb
- source/index.html.md.erb
Adding a new partner-results resource.
Connected with https://github.com/Teamtailor/teamtailor/pull/5255
> Add referrals resource

- bin/setup
- bin/start
- source/includes/candidates/_index.md.erb
Nice to know we havee these around in our projects so you can just run
them to get it all working locally.
> Add bin/setup and bin/start scripts

- source/includes/_changelog.md.erb
- source/includes/requisition_step_verdicts/_index.md.erb
- source/includes/requisition_step_verdicts/_show.md.erb
- source/includes/requisition_step_verdicts/_update.md.erb
- source/includes/requisitions/_index.md.erb
- source/includes/requisitions/_list.md.erb
- source/includes/requisitions/_show.md.erb
- source/index.html.md.erb
Some new [requisition-related endpoints](https://github.com/Teamtailor/teamtailor/pull/6229) were added to Teamtailor's API recently.
This adds some documentation for them. 😊
> Add endpoints for requisitions

- source/includes/_examples.md.erb
With this we have an example of how to create a `To-Many` relationship.
This intercom chat led to this pr:
https://app.intercom.io/a/apps/c3b2d8b8e567c16a39d8495a5b1b2b3865dd4dc7/inbox/inbox/430505/conversations/25641637322
> Add create candidate with location example

- source/includes/_changelog.md.erb
- source/includes/candidates/_create.md.erb
- source/includes/candidates/_index.md.erb
- source/includes/candidates/_list.md.erb
- source/includes/candidates/_read.md.erb
- source/includes/candidates/_update.md.erb
- source/includes/partner_results/_index.md.erb
- source/includes/partner_results/_list.md.erb
- source/includes/partner_results/_read.md.erb
From this PR https://github.com/Teamtailor/teamtailor/pull/8109
> Add new partner-result relations

- source/includes/notes/_create.md.erb
- source/includes/notes/_delete.md.erb
- source/includes/notes/_index.md.erb
- source/includes/notes/_list.md.erb
- source/includes/notes/_read.md.erb
- source/includes/notes/_update.md.erb
- source/index.html.md.erb
> note endpoints

- source/includes/_changelog.md.erb
- source/includes/candidates/_index.md.erb
- source/includes/candidates/_list.md.erb
- source/includes/candidates/_read.md.erb
- source/includes/candidates/_update.md.erb
- source/includes/jobs/_create.md.erb
- source/includes/jobs/_index.md.erb
- source/includes/jobs/_list.md.erb
- source/includes/jobs/_read.md.erb
- source/includes/jobs/_update.md.erb
- source/includes/notes/_create.md.erb
- source/includes/notes/_delete.md.erb
- source/includes/notes/_index.md.erb
- source/includes/notes/_list.md.erb
- source/includes/notes/_read.md.erb
- source/includes/notes/_update.md.erb
- source/includes/regions/_index.md.erb
- source/includes/regions/_list.md.erb
- source/includes/regions/_read.md.erb
- source/index.html.md.erb
> Regions resource and filters

- source/includes/answers/_create.md.erb
> It is not possible to create video or file answer.

- source/includes/candidates/_list.md.erb
Was implemented way back in Teamtailor/teamtailor#939
> Document connected filter

- source/includes/users/_index.md.erb
> Added external recruiter role in user role list

- source/includes/candidates/_index.md.erb
- source/includes/candidates/_list.md.erb
- source/includes/job_applications/_list.md.erb
Related to PR: https://github.com/Teamtailor/teamtailor/pull/9230
> Docs for Candidate/JobApplications date filters

- source/includes/_changelog.md.erb
- source/includes/jobs/_create.md.erb
- source/includes/jobs/_index.md.erb
- source/includes/jobs/_list.md.erb
- source/includes/jobs/_read.md.erb
- source/includes/jobs/_update.md.erb
Adds help text for remote status in docs.
Added to app in this [PR](https://github.com/Teamtailor/teamtailor/pull/9826)
> Remote status on job

- source/index.html.md.erb
> Add missing links to new req routes

- source/includes/_changelog.md.erb
- source/includes/custom-field-options/_create.md.erb
- source/includes/custom-field-options/_index.md.erb
- source/includes/custom-field-options/_update.md.erb
- source/includes/custom-field-selects/_create.md.erb
- source/includes/custom-field-selects/_index.md.erb
- source/includes/custom-field-selects/_update.md.erb
- source/includes/custom-fields/_index.md.erb
- source/includes/custom_field_values/_create.md.erb
- source/includes/custom_field_values/_index.md.erb
- source/includes/custom_field_values/_list.md.erb
- source/index.html.md.erb
This PR updates the documentation for Custom Fields and adds documentation for Custom Field Selects and Options.
This PR is part of a fix for https://github.com/Teamtailor/teamtailor/issues/10277
> Documentation for custom field selects

- source/includes/notes/_create.md.erb
Fixes: https://github.com/Teamtailor/teamtailor/issues/10805
Sorry about the branch name, slippery fingers and mind.🧈
> Fix: Change create notes endpoint to the correct one

- source/includes/uploads/_create.md.erb
> Fix CURL example for create uploads

- source/includes/_intro.md.erb
- source/includes/_postman.md.erb
- source/index.html.md.erb
- source/layouts/layout.erb
- source/stylesheets/custom.css.scss
Added link to Postman request schema
> Add Postman schema

- source/includes/departments/_create.md.erb
- source/includes/departments/_index.md.erb
- source/includes/departments/_list.md.erb
- source/includes/departments/_read.md.erb
- source/includes/departments/_update.md.erb
Fixes: https://github.com/Teamtailor/teamtailor/issues/11161 
Adrian will change it manually in the new postman docs later today (since we have no other way of handling it at the moment).
> Fix: Remove old department attributes

- source/includes/_postman.md.erb
- source/layouts/layout.erb
> Shared docs url
